openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8088
    description: Generated server url
tags:
  - name: Notification
    description: Service notification
paths:
  /api/v1/notifications:
    get:
      tags:
        - Notification
      summary: Get all notifications
      operationId: findAll
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    Notification:
      type: object
      properties:
        idNotification:
          type: string
        type:
          type: string
        message:
          type: string
        registerDate:
          type: string
          format: date-time
        status:
          type: boolean
